### ISSUE TITLE
 Failed building wheel for tulipy

### ISSUE THREAD

**Issue by Sungod3000** [cirla/tulipy#25] opened 2018-10-06 08:53 UTC
Hi,

im trying to install tulipy but im getting this error. I got something similar when installing talib, which had something todo with 32/64bit systems. If this is similar are there any precompiled versions that I can install manually?

Cheers

> Failed building wheel for tulipy
> Command "k:\anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\FRIEDE~1\\AppData\\Local\\Temp\\pip-install-nznwy1d7\\tulipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\FRIEDE~1\AppData\Local\Temp\pip-record-jfbxvjth\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\FRIEDE~1\AppData\Local\Temp\pip-install-nznwy1d7\tulipy\

**Comment by cirla** [comment] 2018-10-16 01:04
Which version of Python? I think the issue is that the Tulip Indicators C library is written in C99 which isn't supported by VC9 which is required to build C modules for Python 2.7, so I can only currently support Python 3.5+ on Windows.

**Comment by cirla** [comment] 2019-04-11 02:38
Closing as `tulipy` cannot support Python < 3.5 on Windows.

**Closed by cirla** 2019-04-11 02:38 UTC
